USE [master]
GO

/****** Object:  Database [constructiondb]    Script Date: 19-10-2025 00:50:50 ******/
CREATE DATABASE [constructiondb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'constructiondb', FILENAME = N'C:\Users\msi\constructiondb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'constructiondb_log', FILENAME = N'C:\Users\msi\constructiondb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [constructiondb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [constructiondb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [constructiondb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [constructiondb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [constructiondb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [constructiondb] SET ARITHABORT OFF 
GO

ALTER DATABASE [constructiondb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [constructiondb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [constructiondb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [constructiondb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [constructiondb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [constructiondb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [constructiondb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [constructiondb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [constructiondb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [constructiondb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [constructiondb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [constructiondb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [constructiondb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [constructiondb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [constructiondb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [constructiondb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [constructiondb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [constructiondb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [constructiondb] SET  MULTI_USER 
GO

ALTER DATABASE [constructiondb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [constructiondb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [constructiondb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [constructiondb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [constructiondb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [constructiondb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [constructiondb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [constructiondb] SET  READ_WRITE 
GO

