// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Construction.Entity.Models;

public partial class constructiondbContext : DbContext
{
    public constructiondbContext(DbContextOptions<constructiondbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MaterialType> MaterialTypes { get; set; }

    public virtual DbSet<Organisation> Organisations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Site> Sites { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Userrole> Userroles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MaterialType>(entity =>
        {
            entity.HasKey(e => e.MaterialTypeId).HasName("PK__Material__1621BBDF56A13322");

            entity.ToTable("MaterialType");

            entity.Property(e => e.MaterialTypeId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DefaultUnit).HasMaxLength(50);
            entity.Property(e => e.MaterialName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Organisation>(entity =>
        {
            entity.ToTable("Organisation");

            entity.Property(e => e.OrganisationId)
                .ValueGeneratedNever()
                .HasColumnName("organisationId");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.OrganisationName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("organisationName");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Roleid).HasName("PK_role");

            entity.ToTable("Role");

            entity.Property(e => e.Roleid)
                .ValueGeneratedNever()
                .HasColumnName("roleid");
            entity.Property(e => e.Organisationid).HasColumnName("organisationid");
            entity.Property(e => e.Rolename)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("rolename");
        });

        modelBuilder.Entity<Site>(entity =>
        {
            entity.ToTable("Site");

            entity.Property(e => e.Siteid)
                .ValueGeneratedNever()
                .HasColumnName("siteid");
            entity.Property(e => e.Isactive).HasColumnName("isactive");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .HasColumnName("location");
            entity.Property(e => e.Organisationid).HasColumnName("organisationid");
            entity.Property(e => e.Sitename)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("sitename");
            entity.Property(e => e.Userid).HasColumnName("userid");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.ToTable("Supplier");

            entity.Property(e => e.SupplierId).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(250);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.SupplierContactPerson).HasMaxLength(150);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("user");

            entity.Property(e => e.Userid)
                .ValueGeneratedNever()
                .HasColumnName("userid");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Contactnumber)
                .HasMaxLength(20)
                .HasColumnName("contactnumber");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Firstname).HasMaxLength(100);
            entity.Property(e => e.Isactive).HasColumnName("isactive");
            entity.Property(e => e.Lastname).HasMaxLength(100);
            entity.Property(e => e.Password).HasMaxLength(256);
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
            entity.Property(e => e.Wageperday)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("wageperday");
        });

        modelBuilder.Entity<Userrole>(entity =>
        {
            entity.HasKey(e => e.Userroleid).HasName("PK__userrole__F07D108A458BC3E7");

            entity.ToTable("userrole");

            entity.Property(e => e.Userroleid)
                .ValueGeneratedNever()
                .HasColumnName("userroleid");
            entity.Property(e => e.Roleid).HasColumnName("roleid");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}