// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class EmployeeAttendance
{
    public Guid AttendanceId { get; set; }

    public string EmployeeName { get; set; }

    public string AttendanceStatus { get; set; }

    public decimal? OvertimeHrs { get; set; }

    public Guid SiteId { get; set; }

    public Guid OrganisationId { get; set; }

    public Guid UserId { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }
}