// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class ExpenseCategory
{
    public Guid ExpenseCategoryId { get; set; }

    public string ExpenseCategoryName { get; set; }

    public Guid OrganisationId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }
}