// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class LabourPayment
{
    public Guid LabourPaymentId { get; set; }

    public decimal Amount { get; set; }

    public string Notes { get; set; }

    public Guid SiteId { get; set; }

    public DateTime PaymentPeriodStartDate { get; set; }

    public DateTime PaymentPeriodEndDate { get; set; }

    public Guid? OrganisationId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid? UserId { get; set; }
}