// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class Role
{
    public Guid Roleid { get; set; }

    public string Rolename { get; set; }

    public Guid Organisationid { get; set; }
}