// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class Site
{
    public Guid Siteid { get; set; }

    public string Sitename { get; set; }

    public string Location { get; set; }

    public bool Isactive { get; set; }

    public Guid Organisationid { get; set; }

    public Guid? Userid { get; set; }
}