// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class Userrole
{
    public Guid Userroleid { get; set; }

    public Guid Roleid { get; set; }

    public Guid? UserId { get; set; }
}