// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Construction.Entity.Models;

public partial class User
{
    public Guid Userid { get; set; }

    public bool Isactive { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string City { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Contactnumber { get; set; }

    public decimal? Wageperday { get; set; }

    public string Address { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid OrganisationId { get; set; }
}